version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - thinceller
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: swr
    versions:
    - 0.5.2
    - 0.5.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: next
    versions:
    - 10.0.9
  - dependency-name: "@types/draft-js"
    versions:
    - 0.10.45
  - dependency-name: next-transpile-modules
    versions:
    - 6.1.0
  - dependency-name: immer
    versions:
    - 9.0.0
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - thinceller
